### ISSUE TITLE
Publish version supporting dropwizard 0.9.1

### ISSUE THREAD

**Issue by beresfordt** [service-enabled/dropwizard-request-tracker#32]
The most recently published version available in maven central is 0.2.0, which is aimed at dropwizard 0.7.1

It looks like the current version is aimed at dropwizard 0.9.1 - could this please be published to maven central?

**Comment by JonMR** [comment]
Can do. Should be able to get it published this weekend.

**Comment by JonMR** [comment]
Done! Honestly, thanks for the nudge. Sorry for the delay.

**Comment by beresfordt** [comment]
Brilliant - many thanks!
