### ISSUE TITLE
Use JUnit 5

### ISSUE THREAD

**Issue by JonMR** [service-enabled/dropwizard-request-tracker#35]
Split from #33.

See my [comment](https://github.com/service-enabled/dropwizard-request-tracker/issues/33#issuecomment-429432111) which discusses some of JUnit 5 and dropwizard.

The tricky part will be the removal of rules. Since we wrap one rule with another rule. Need to figure out how to do that with extensions.

This will have to be built on top of #34 since JUnit 5 requires Java 8.

**Comment by darkmoonka** [comment]
Hi @JonMR,
can you please assign this to me? I would push my solution
